# AppVeyor configuration for EPICS Base

# Ralph Lange <ralph.lange@gmx.de>
# Copyright (c) 2016-2017 ITER Organization

# Version format
version: base-{branch}-{build}

#---------------------------------#
#       repository cloning        #
#---------------------------------#

# Called at very beginning, before repo cloning
init:
  # Set autocrlf to make batch files work
  - git config --global core.autocrlf true

# Set clone depth (do not fetch complete history)
clone_depth: 50

# Skipping commits affecting only specific files
skip_commits:
  files:
    - 'documentation/*'
    - 'templates/*'
    - '**/*.html'
    - '**/*.md'

#---------------------------------#
#   build matrix configuration    #
#---------------------------------#

# Build Configurations: dll/static, regular/debug
configuration:
  - dynamic

# Environment variables: compiler toolchain
environment:
  matrix:
  - TOOLCHAIN: 10.0
    APPVEYOR_RDP_PASSWORD: St0pidM$

# Platform: architecture
platform:
  - x64

# Matrix configuration: allow specific failing jobs
matrix:
  exclude:
  # VS Express installs don't have the 64 bit compiler
  - platform: x64
    TOOLCHAIN: 10.0
  # Cygwin static-debug has compiler problems
  - configuration: static-debug
    TOOLCHAIN: cygwin
  # Cygwin x86 install is currently (08/2019) broken (libncursesw-devel fails)
  - platform: x86
    TOOLCHAIN: cygwin


#---------------------------------#
#     building & testing          #
#---------------------------------#

install:
  - cmd: git submodule update --init --recursive
  - cmd: .ci/appveyor-prepare.bat

build_script:
  - cmd: .ci/appveyor-make.bat

test_script:
  - cmd: .ci/appveyor-make.bat runtests

artifacts:
  - path: '**/*.tap'
    name: tap.zip
    type: zip

on_failure:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

