sudo: required
dist: trusty
language: c
compiler:
  - gcc
env:
  - RTEMS=4.9
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - clang
    - qemu-system-x86
script: sh build-travis.sh
