language: c
compiler:
  - gcc
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - clang
    - g++-mingw-w64-i686
    - bison
    - flex
    - texinfo
    - install-info
    - qemu-system-x86

script: sh ci/travis-build.sh </dev/null
matrix:
  include:
  - os: linux
    sudo: false
    dist: trusty
    env: CMPLR=gcc
  - os: osx
    osx_image: xcode8
    env: CMPLR=gcc
