language: c

matrix:
  include:
    - sudo: false
      dist: trusty
      compiler: gcc
      env: CMPLR=gcc
    - sudo: false
      dist: trusty
      compiler: gcc
      env: CMPLR=gcc EXTRA=CMD_CXXFLAGS=-std=c++11
    - sudo: false
      dist: trusty
      compiler: gcc
      env: CMPLR=gcc STATIC=YES
    - sudo: false
      dist: trusty
      compiler: gcc
      env: CMPLR=clang
    - sudo: false
      dist: trusty
      compiler: gcc
      env: CMPLR=clang STATIC=YES
    - sudo: false
      dist: trusty
      compiler: gcc
      env: WINE=32 TEST=NO STATIC=YES
    - sudo: false
      dist: trusty
      compiler: gcc
      env: WINE=32 TEST=NO STATIC=NO
    - sudo: false
      dist: trusty
      compiler: gcc
      env: RTEMS=4.10 TEST=YES
    - sudo: false
      dist: trusty
      compiler: gcc
      env: RTEMS=4.9 TEST=YES
    - os: osx
      env: EXTRA=CMD_CXXFLAGS="-std=c++98 -stdlib=libstdc++"

addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - clang
    - g++-mingw-w64-i686
    - qemu-system-x86

script: sh .ci/travis-build.sh </dev/null
