sudo: required
dist: trusty
language: c
compiler:
  - gcc
env:
  - CMPLR=gcc
  - CMPLR=gcc STATIC=YES
  - CMPLR=clang
  - CMPLR=clang STATIC=YES
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - clang
script: sh build-travis.sh
